# Generated by Django 4.1 on 2022-11-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
        ('submission', '0006_rename_authors_submission_authors_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsGeneral',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.CharField(max_length=15)),
                ('endTime', models.CharField(max_length=15)),
                ('program', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('isParallel', models.BooleanField()),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='speakers.speakers')),
            ],
        ),
        migrations.CreateModel(
            name='EventsParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.CharField(max_length=15)),
                ('endTime', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=50)),
                ('eventId', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.eventsgeneral')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='submission.track')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='speakers.speakers')),
            ],
        ),
    ]
