# Generated by Django 4.1 on 2022-10-30 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsBBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsCPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsECE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsISBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsMME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsSBCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionsSCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('author', models.TextField()),
                ('paper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium', models.CharField(max_length=20)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium_T', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parallel_sessions.tracks')),
            ],
        ),
    ]
