# Generated by Django 4.1 on 2022-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
                ('web_page', models.URLField()),
                ('person_id', models.IntegerField()),
                ('correspon', models.BooleanField(null=True)),
                ('full_name', models.TextField()),
            ],
        ),
    ]
