# Generated by Django 4.1 on 2022-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='submission_id',
            field=models.CharField(max_length=30),
        ),
    ]
