# Generated by Django 4.1 on 2022-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authors_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='organization',
            field=models.CharField(max_length=100),
        ),
    ]
