# Generated by Django 4.1 on 2022-11-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_authors_country_alter_authors_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='organization',
            field=models.CharField(max_length=200),
        ),
    ]
