# Generated by Django 4.1 on 2022-10-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('symposium', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('submitted', models.DateTimeField()),
                ('lastUpdated', models.DateTimeField()),
                ('keywords', models.TextField()),
                ('decison', models.TextField()),
                ('notified', models.BooleanField()),
                ('reviewsSent', models.BooleanField()),
                ('abstract', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('chair', models.TextField()),
                ('trackId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='submission.track')),
            ],
        ),
    ]
