# Generated by Django 4.1 on 2022-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_rename_decison_submission_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TextField(),
        ),
    ]
