# Generated by Django 4.1 on 2022-10-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='notified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewsSent',
            field=models.BooleanField(null=True),
        ),
    ]
