# Generated by Django 4.1 on 2022-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_submission_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.CharField(default='null', max_length=5),
            preserve_default=False,
        ),
    ]
